// Generated by https://quicktype.io

export interface GetDispute {
    dispute_id:               string;
    create_time:              string;
    update_time:              string;
    disputed_transactions:    DisputedTransaction[];
    reason:                   string;
    status:                   string;
    dispute_amount:           Amount;
    dispute_outcome:          DisputeOutcome;
    dispute_life_cycle_stage: string;
    dispute_channel:          string;
    messages:                 Message[];
    offer:                    Offer;
    links:                    Link[];
}

export interface Amount {
    currency_code: string;
    value:         string;
}

export interface DisputeOutcome {
    outcome_code: string;
}

export interface DisputedTransaction {
    buyer_transaction_id:       string;
    seller_transaction_id:      string;
    create_time:                string;
    transaction_status:         string;
    gross_amount:               Amount;
    buyer:                      Buyer;
    seller:                     Seller;
    seller_protection_eligible: boolean;
}

export interface Buyer {
    email:    string;
    payer_id: string;
    name:     string;
}

export interface Seller {
    email:       string;
    merchant_id: string;
    name:        string;
}

export interface Link {
    href:   string;
    rel:    string;
    method: string;
}

export interface Message {
    posted_by:   string;
    time_posted: string;
    content:     string;
}

export interface Offer {
    buyer_requested_amount: Amount;
}
