// Generated by https://quicktype.io

export interface ListDisputes {
    items: Item[];
    links: Link[];
}

export interface Item {
    dispute_id:     string;
    create_time:    string;
    update_time:    string;
    reason:         string;
    status:         string;
    dispute_amount: DisputeAmount;
    links:          Link[];
}

export interface DisputeAmount {
    currency_code?: string;
    value?:         string;
}


export interface Link {
    href:     string;
    rel: string;
    method: string;
    encType?: string;
}

