// Generated by https://quicktype.io

export interface Token {
    scope:                   string;
    nonce:                   string;
    access_token:            string;
    token_type:              string;
    app_id:                  string;
    expires_in:              number;
    supported_authn_schemes: string[];
}
